<?php
define("page title",'Frequently asked questions');
define("page keywords",'faq, ask, answer');
define("page description",'frequently asked questions');
define('page heading','FAQ (frequently asked questions)');
define('zp1','Have trouble to log in?');
define('zp2','– Probably you are trying to login with your previous account.');
define('zp3','What happened to my previous account?');
define('zp4','– We are deeply sorry to announce that up-to version 3 accounts, comments and lyrics are not active anymore as we are upgrading totally to a new version on App Engine.');
define('zp5','– Lyrics and comments will be transferred later manually.');
define('zp6','Who can register and become a member?');
define('zp7','– Everyone is invited to become a member through our registration form.');
define('zp8','Why do I have to be a registered member?');
define('zp9','– By becoming a registered member of Zaideih, you will be able to create your own music collection, create your playlist and share.');
define('zp10','– Any of your posted lyrics and comments will be directly available to public without getting approval by managers and can be edited later.');
define('zp11','– To be able to download and upload music.');
define('zp12','– To add star to your favorite music.');
define('zp13','– The primary step of becoming a Zaideih partner is to be a registered member.');
define('zp14','What is the aim with Zaideih?');
define('zp15','– Our aim and objective is to make Christian worship music available around the world and to be a place where people can discover God’s mercy, will and love.');
define('zp16','What is Zaideih?');
define('zp17','– Sing songs happily or gladly/amuse by singing.');
define('zp18','Can I listen to music on other devices?');
define('zp19','– We are working to get it available on iOS and Android.');
define('zp20','What type of music is available?');
define('zp21','– Most of the audio data available on Zaideih is Myanmar Christian music, Zomi, Mizo, Falam, Hakha and is released in Myanmar, Thailand, Malaysia and India. Some English music like hymn, gospel and praise & worship music are also available to listen.');
define('zp22','– We do not deselect any Myanmar Christian music or tribal related music on Zaideih.');
define('zp23','– If you find that something is not available, you can give us a suggestion about adding it.');
define('zp24','Is the music downloadable?');
define('zp25','– Yes, for users with Zaideih credit.');
define('zp26','– Albums or tracks that are not active in the market might be available to download, but it also depends on permission from the owner/copyright holder.');
define('zp27','How can I download?');
define('zp28','– It can only be downloaded if you have a permission to download, but you can earn Zaideih credits to download your favorite music by posting lyrics, tabs and commenting tracks.');
define('zp29','How can I upload?');
define('zp30','– Only a Zaideih partner can upload music.');
define('zp31','How can I delete my account?');
define('zp32','– You will find this function inside your profile. A deletion cannot be undone.');
define('zp33','How can I become a partner?');
define('zp34','– Register as a member or inform us that you would like to become one.');
define('zp35','– For registered member -> check {apply for partner} in your profile and wait for approval. All you have to do is click.');
define('zp36','How much does it cost to be a partner?');
define('zp37','– Nothing. It’s free.');
define('zp38','For how long will Zaideih have free music streaming?');
define('zp39','– Zaideih will serve as long as we can afford it’s costs. Those members who have uploaded data will get notified in no less than 90 days before we stop our service.');
define('zp40','– As we have started already we will not just stop and surrender easily.');
define('zp41','Found incorrect information on albums or tracks?');
define('zp42','– We are much much delighted to be informed and given correct information about artists names, tracks and album titles, year, copyright, studio, band etc.');
define('zp43','If you find incorrect information, it means we do not have enough information of the object (album, track, artist).');
define('zp44','About my account information.');
define('zp45','– Any of your own information that you have mentioned in your profile will never be available publicly unless you have shared it. We have provided sufficient options for your profile like email and phone hiding, etc.');
define('zp46','– Sharing your playlist and favorite music does not mean your profile has been shared.');
define('zp47','What is a playlist?');
define('zp48','– A playlist is a collection of your own favorite music. With the playlists you can have a category structure and it can be shared to other users.');
define('zp49','What is star?');
define('zp50','– Star at Zaideih is similar to like or +1, but we have 4 different stars (like, top, all the time, note)');
define('zp51','What is contribution?');
define('zp52','– Contribution is a form that collect tags about artists, tracks (genre, year, band, copyright, etc.) and album title. Contribution form is available on all of our music pages at the right menu.');