<?php
define("page title",'About us');
define("page keywords",'zaideih, music');

define('zp0','About us');
define('zp1','Our aim and objective is to make Christian worship music available around the world and to be a place where people can discover God’s mercy, will and love. We hope Zaideih can be an oasis where people can be united through their love of worship music, and we hope it can be a place where people can find out how many languages are used in this world to worship God. Even though we speak different languages, some big and some small, in the the eyes of the Creator we are all the same and all worship music has the same value. To get a true closeness to the Lord, be believe it is important to listen and sing worship music on the language that is closest to heart, our mother tongue. That is why we want to give people all over the world the opportunity to listen to worship music on their own language.');
define('zp2','Zaideih started in 2006 on a free web hosting as online music streaming for Myanmar gospel songs (Christian music) and other tribal music such as Zomi, Mizo, Falam, Hakha etc. After some advices from friends (Thang Biak Lal, Paupi, Cinpu), it got the name Zaideih. It launched in 2007 on it’s own domain name in New Delhi, India, with no more than 200 songs. I started it because there was no other online music streaming for Myanmar Christian music and I was hungry to listen at work when I worked as a web developer at Micro Computer Service. In 2008 more than 4000 songs in Zomi language (spoken natively in Myanmar and India) and 4000 songs in Mizo language (spoken natively in Myanmar, India and Bangladesh) were added. In 2009, some users recognized it as the Zaideih Music Station. Zaideih is a word in Zomi language with the meaning “sing songs happily” and Zaideih started with music in Zomi language. But our hope is that worship music on many more languages will be added later.');
define('zp3','The design of Zaideih has been changed for three times, but hopefully this will be the last design. The web hosting has been changed four times due to the limitation of shared hosting (bandwidth limit, storage limit etc.). Zaideih has gotten donations through Paypal from Lianpi, Neihmung, Biaklian, Taang Sianpu, Sian Lian, Zomidaily and Lian Piang and for this I am very grateful. Zaideih is running on Google App Engine now and it’s developed and maintained by ZOTUNE.developer. By becoming a registered member of Zaideih, you are now able to create your own music collections, create playlists and share. You can also add a star to your favorite music.');
define('zp4','We want listeners and copyright holders to understand the sources of the music and data found on Zaideih, and we would like to give you some information about why Zaideih Music Station make it available. First of all, we would like to mention straight that Zaideih Music Station does not own each and every data which is being streamed. Our aim and objective is to make available Christian music around the world and be a place where people can discover God’s mercy, will and love. You will not be asked anything if you want to listen to music on this site, it’s free of costs. Zaideih is a free music site and does not charge users for its usage. Thereby, it does not derive any profit by making the data/music available in the website. Hence, it is difficult for us to contact and request permission from every copyright holder/owner of the music that is being streamed. Therefore, we humbly seek special understanding from owners, copyright holders, artists, and everyone who is associated with the music streamed on this site. It is our objective to show the world your hard work and to promote every artist. Zaideih Music Station is also very much committed to respect each material’s market and owner’s business by not streaming music that has been active on the market recently. Members who have applied to become Zaideih partners are free to upload audio files. Other members can only do so if it is their own data.');
define('zp5','Honored copyright holders, if you have opinions about the way we make music available on this site, please feel free to give us your opinion about it. We will of course respond to you.');
define('zp6','Dear Zaideih visitors, please enjoy the music, but do not forget to purchase the original music whenever you feel like listening while offline or playing in another device that Zaideih does not support yet.');
define('zp7','Feel free to contact us if you have any questions, or if you want to give any comments or suggestions.');