<?php 
define("page title",'Terms of service');
define("page keywords",'Terms of service, User License, Content, Proprietary Rights, Fees');
define("page description",'By using the Zaideih Music Station services');
define("zt1",'Terms of service');

define('zp0','Terms of service');
define('zp1','By using the Zaideih Music Station services, you agree to be bound by this terms of use agreement, whether you are a "visitor" (which means that you simply browse the Zaideih Music Station website) or you are a "member" (which means that you have registered with Zaideih Music Station). The term "user" refers to a visitor or a member. You are only authorized to use the Zaideih Music Station’s services (regardless of whether your access or use is intended) if you agree to abide by all applicable laws and to this agreement. Please read this agreement carefully and save it. By accessing {www}, you are agreeing to be bound by these website terms and conditions of use, all applicable laws and regulations, and agree that you are responsible for compliance with any applicable local laws. If you do not agree with any of these terms, you are prohibited from using or accessing this site.');
define('zp2','User License');
define('zp3','Permission is granted for Zaideih partners to temporarily download one copy of the materials (information or software) on Zaideih Music Station’s web site for personal, non-commercial transitory viewing only. This is the grant of a license, not a transfer of title, and under this license you may not:');
define('zp4','modify or copy the materials;');
define('zp5','use the materials for any commercial purpose, or for any public display (commercial or non-commercial);');
define('zp6','attempt to decompile or reverse engineer any data contained on Zaideih Music Station’s web site;');
define('zp7','remove any copyright or other proprietary notations from the materials; or');
define('zp8','transfer the materials to another person or “mirror” the materials on any other server.');
define('zp9','This license shall automatically terminate if you violate any of these restrictions and may be terminated by Zaideih Music Station at any time. Upon terminating your viewing of these materials or upon the termination of this license, you must destroy any downloaded materials in your possession whether in electronic or printed format.');
define('zp10','Content');
define('zp11','Please choose carefully the information you post on Zaideih Music Station and that you provide to other users. Your Zaideih Music Station profile may not include the following items: any photographs containing nudity, or illegal, obscene, lewd, excessively violent, harassing, sexually explicit or otherwise objectionable subject matter. Despite this prohibition, information provided by other Zaideih Music Station members (for instance, in their profile) may contain inaccurate, inappropriate, offensive or sexually explicit material, products or services, and Zaideih Music Station assumes no responsibility or liability for this material. If you become aware of misuse of the Zaideih Music Station’s services by any person, please contact us.');
define('zp12','Zaideih Music Station reserves the right, in its sole discretion, to edit, reject, refuse to post or remove any posting (including private messages) by you, or to restrict, suspend, or terminate your access to all or any part of the Zaideih Music Station’s services at any time, for any or no reason, with or without prior notice, and without liability. Zaideih Music Station expressly reserves the right to remove your profile and/or restrict, suspend, or terminate your access to any part of {www} if Zaideih Music Station determines, in its sole discretion, that you pose a threat to the site and/or its users.');
define('zp13','Proprietary Rights');
define('zp14','Zaideih Music Station does not claim any ownership rights in the text, files, images, photos, videos, sounds, musical works, works of authorship, or any other materials (collectively, "content") that you post. After posting your content to Zaideih Music Station, you continue to retain all ownership rights, and you continue to have the right to use your content in any way you choose.');
define('zp15','Fees');
define('zp16','Use of the Zaideih Music Station’s services is currently free of charge but may not always remain that way. You acknowledge that we reserve the right to charge for Zaideih Music Station’s services and to change its fees from time to time in its discretion. If Zaideih Music Station terminates your membership because you have breached the agreement, you shall not be entitled to the refund of any unused portion of subscription fees.');
define('zp17','Email and Password');
define('zp18','When you sign up to become a Member, you will also be asked to enter your email address and choose a password. You are entirely responsible for maintaining the confidentiality of your email and password. You agree not to use the account, username, or password of another member at any time or to disclose your password to any third party. You agree to notify Zaideih Music Station immediately if you suspect any unauthorized use of your account or access to your email and/or password. You are solely responsible for any and all use of your account.');
define('zp19','Non-commercial Use by Members');
define('zp20','Zaideih Music Station’s services are for the personal use of members only and may not be used in connection with any commercial endeavors except those that are specifically endorsed or approved by us. Illegal and/or unauthorized use of the Zaideih Music Station’s services, including collecting usernames and/or email addresses of members by electronic or other means for the purpose of sending unsolicited email or unauthorized framing of or linking to the {www} website is prohibited. Commercial advertisements, affiliate links, and other forms of solicitation may be removed from member profiles without notice and may result in termination of membership privileges. Appropriate legal action will be taken for any illegal or unauthorized use of Zaideih Music Station’s services.');
define('zp21','Revisions and Errata');
define('zp22','The materials appearing on Zaideih Music Station\'s web site could include technical, typographical, or photographic errors. Zaideih Music Station does not warrant that any of the materials on its web site are accurate, complete, or current. Zaideih Music Station may make changes to the materials contained on its web site at any time without notice. Zaideih Music Station does not, however, make any commitment to update the materials.');
define('zp23','Links');
define('zp24','Zaideih Music Station has not reviewed all of the sites linked to its Internet web site and is not responsible for the contents of any such linked site. The inclusion of any link does not imply endorsement by Zaideih Music Station of the site. Use of any such linked web site is at the user’s own risk.');
define('zp25','Site Terms of Use Modifications');
define('zp26','Zaideih Music Station may revise these terms of use for its web site at any time without notice. Such modification shall be effective upon posting on the Zaideih Music Station website. By using this web site you are agreeing to be bound by the then current version of these terms and conditions of use. It is therefore important that you review this agreement regularly to ensure you are updated as to any changes.');
?>